services:
  tts-indic-server:
    image: slabstech/tts_indic_server_cpu
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 7860:7860
    environment:
      - LANGUAGE=kn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]